name: Deploy Infrastructure

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ 'infra/**' ]

permissions:
  contents: read

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: false
          allow-no-subscriptions: false

      - name: Create Resource Group
        run: |
          az group create \
            --name rg-simple-func-iac \
            --location westeurope \
            --output none

      - name: Test Azure CLI Connection
        run: |
          az account show --output table
          az group list --output table

      - name: Deploy Infrastructure with GitHub Actions
        uses: azure/arm-deploy@v1
        id: deploy-infra
        with:
          resourceGroupName: rg-simple-func-iac
          template: infra/main.bicep
          parameters: >
            functionAppName=simple-func-iac-ba
            storageAccountName=simplefunciacba
            appInsightsName=simple-func-iac-ba-insights
            hostingPlanName=simple-func-iac-ba-plan
          deploymentMode: Incremental
          deploymentName: infrastructure-deployment
          failOnStdErr: false

      - name: Get Function App Name
        id: get-function-app
        run: |
          echo "function-app-name=${{ steps.deploy-infra.outputs.functionAppName }}" >> $GITHUB_OUTPUT

      - name: Show Deployment Results
        run: |
          echo "=== Deployment Completed Successfully ==="
          echo "Function App Name: ${{ steps.deploy-infra.outputs.functionAppName }}"
          echo "Function App URL: ${{ steps.deploy-infra.outputs.functionAppUrl }}"
          echo "Storage Account: ${{ steps.deploy-infra.outputs.storageAccountName }}"
          echo "App Insights: ${{ steps.deploy-infra.outputs.appInsightsName }}"
          echo "=== Next Steps ==="
          echo "1. Run the 'Deploy Function App' workflow to deploy the function code"
          echo "2. Test the endpoints after deployment"